"""Tests for YAML utility functions."""

from gl2gh.utils.yaml_utils import (
    add_yaml_header,
    dump_yaml,
    load_yaml_with_anchors,
    validate_yaml_syntax,
)


class TestLoadYamlWithAnchors:
    def test_simple_yaml(self):
        result = load_yaml_with_anchors("foo: bar\nbaz: 1")
        assert result["foo"] == "bar"
        assert result["baz"] == 1

    def test_empty_string(self):
        result = load_yaml_with_anchors("")
        assert result == {}

    def test_anchors_resolved(self):
        content = """\
defaults: &defaults
  image: python:3.11
  tags:
    - docker

job:
  <<: *defaults
  script: echo hi
"""
        result = load_yaml_with_anchors(content)
        assert result["job"]["image"] == "python:3.11"

    def test_non_dict_returns_empty(self):
        result = load_yaml_with_anchors("- a\n- b")
        assert result == {}


class TestDumpYaml:
    def test_round_trip(self):
        data = {"name": "CI", "on": {"push": {}}, "jobs": {}}
        output = dump_yaml(data)
        assert "name: CI" in output
        # 'on' key should be quoted to avoid YAML 1.1 bool
        assert '"on"' in output

    def test_nested_structure(self):
        data = {"jobs": {"build": {"runs-on": "ubuntu-latest"}}}
        output = dump_yaml(data)
        assert "runs-on: ubuntu-latest" in output


class TestAddYamlHeader:
    def test_header_present(self):
        result = add_yaml_header("name: CI", ".gitlab-ci.yml")
        assert "Auto-generated by gl2gh" in result
        assert ".gitlab-ci.yml" in result
        assert result.endswith("name: CI")

    def test_custom_source(self):
        result = add_yaml_header("name: CI", "custom/path.yml")
        assert "custom/path.yml" in result


class TestValidateYamlSyntax:
    def test_valid_yaml(self):
        assert validate_yaml_syntax("foo: bar") is None

    def test_invalid_yaml(self):
        result = validate_yaml_syntax("foo: [bar: {{")
        assert result is not None
        assert isinstance(result, str)

    def test_empty_is_valid(self):
        assert validate_yaml_syntax("") is None
