"""YAML parsing and serialization utilities."""

from __future__ import annotations
import re
from typing import Any, Optional
from io import StringIO
import yaml
from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq
from ruamel.yaml.scalarstring import DoubleQuotedScalarString


def load_yaml(content: str) -> dict[str, Any]:
    return yaml.safe_load(content) or {}


def load_yaml_with_anchors(content: str) -> dict[str, Any]:
    ry = YAML()
    ry.preserve_quotes = True
    result = ry.load(content)
    if result is None:
        return {}
    return _ruamel_to_dict(result)


def _ruamel_to_dict(obj: Any) -> Any:
    if isinstance(obj, CommentedMap):
        return {k: _ruamel_to_dict(v) for k, v in obj.items()}
    elif isinstance(obj, CommentedSeq):
        return [_ruamel_to_dict(i) for i in obj]
    return obj


def _dict_to_commented(obj: Any) -> Any:
    """Convert plain dicts to CommentedMap, quoting the 'on' key to avoid YAML 1.1 bool."""
    if isinstance(obj, dict):
        cm = CommentedMap()
        for k, v in obj.items():
            key = DoubleQuotedScalarString(k) if k == "on" else k
            cm[key] = _dict_to_commented(v)
        return cm
    elif isinstance(obj, list):
        return [_dict_to_commented(i) for i in obj]
    return obj


def dump_yaml(data: dict[str, Any], sort_keys: bool = False) -> str:
    ry = YAML()
    ry.default_flow_style = False
    ry.indent(mapping=2, sequence=4, offset=2)
    ry.width = 120
    # Convert to CommentedMap so we can control quoting of 'on' key
    # YAML 1.1 treats bare 'on' as boolean True, so it must be quoted
    cm = _dict_to_commented(data)
    stream = StringIO()
    ry.dump(cm, stream)
    return stream.getvalue()


def add_yaml_header(content: str, source_file: str = ".gitlab-ci.yml") -> str:
    header = f"""# ============================================================
# Auto-generated by gl2gh (GitLab CI -> GitHub Actions)
# Source: {source_file}
# ============================================================
# Review this file before committing:
#   - Check branch/tag trigger patterns
#   - Verify secret names (CI vars -> GitHub Secrets)
#   - Test with: gh workflow run <workflow-name>
# ============================================================

"""
    return header + content


def validate_yaml_syntax(content: str) -> Optional[str]:
    try:
        yaml.safe_load(content)
        return None
    except yaml.YAMLError as e:
        return str(e)


def normalize_script_step(script: str | list[str]) -> list[str]:
    if isinstance(script, str):
        return [script]
    return list(script)
